use std::error::Error;

pub fn questionmark(foreign_error: Result<(), impl Error>) -> anyhow::Result<()> {
    todo!()
}
